# Generated by Django 3.0.4 on 2020-04-14 17:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationSportBeauty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_place', models.TextField(blank=True, null=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('time', models.TimeField()),
                ('number_people', models.IntegerField()),
            ],
        ),
    ]
