# Generated by Django 3.0.4 on 2020-04-14 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form_sport_beauty', '0002_category_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationsportbeauty',
            name='name_place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='form_sport_beauty.Item'),
        ),
    ]
