# Generated by Django 3.0.4 on 2020-04-14 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('form_sport_beauty', '0003_auto_20200414_1803'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrationsportbeauty',
            options={'ordering': ('name_place',)},
        ),
        migrations.AddField(
            model_name='registrationsportbeauty',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
